---
title: "Instalação e Gerenciamento de Pacotes LaTeX com TinyTeX"
author: "César Gabriel"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE, cache=TRUE}
options(repos = c(CRAN = "https://cran.rstudio.com/"))
if (!require("rmarkdown")) {
  install.packages("rmarkdown")
}
```

# Execute o Visual Studio Code como Administrador

## Instalar o Pacote e o TinyTeX

Primeiro, vamos instalar o pacote `tinytex` e o TinyTeX:
```{R, cache=TRUE, eval=FALSE}
if (!require("tinytex")) {
  tinytex::install_tinytex(dir = "C:/Program Files/TinyTex", force = TRUE)
} else {
  library(tinytex)
}
```
Aceite a opção informada com Y.
Adicione o Bin do TinyTex nas variáveis de ambiente do Windows.

## Desinstalar TinyTeX
Para desinstalar o TinyTeX, rode:

```{R, cache=TRUE, eval=FALSE}
tinytex::uninstall_tinytex()
```

## Resolver Problemas
Para tentar resolver problemas, atualize os pacotes e o TinyTeX:

```{R, cache=TRUE}
update.packages(ask = FALSE, checkBuilt = TRUE)
Sys.setenv(PATH = paste("C:/Program Files/TinyTex/bin/windows", Sys.getenv("PATH"), sep = ";"))
tinytex::tlmgr_update()
```

## Reinstalar o TinyTex
Se necessário, reinstale o TinyTeX:

```{R, eval=FALSE, cache=TRUE}
tinytex::reinstall_tinytex()
```

## Instalar Pacotes Específicos
Talvez seja necessário instalar alguns pacotes do documento como abaixo:

```{R, cache=TRUE}
tinytex::tlmgr_install("subfigure")
tinytex::tlmgr_install("bm")
tinytex::tlmgr_install("babel-portuges")
```

## Compilar Documento LaTeX
Para compilar o documento LaTeX:

```{R, eval=FALSE, cache=TRUE}
tinytex::latexmk("main.tex")
```

## Função para Analisar e Instalar Pacotes de um Arquivo .tex
A função abaixo analisa um arquivo .tex, busca os valores dentro de `\usepackage{}` e instala todos de uma vez:

```{R, cache=TRUE,}
instalar_pacotes_tex <- function(file_path) {
  tex_content <- readLines(file_path)
  pacotes <- unlist(regmatches(tex_content, gregexpr("\\\\usepackage\\{([^}]*)\\}", tex_content)))
  pacotes <- gsub("\\\\usepackage\\{|\\}", "", pacotes)
  if (length(pacotes) > 0) {
    tinytex::tlmgr_install(pacotes)
  } else {
    message("Nenhum pacote encontrado no arquivo .tex")
  }
}
# instalar os pacotes necessários do arquivo main.tex
instalar_pacotes_tex("main.tex")
```

## Caminho do LaTeX
O caminho onde o LaTeX está instalado:

```{R, eval=FALSE, cache=TRUE}
"C:\Program Files\TinyTex\bin\windows\pdflatex.exe"
```
